version: '3.8'
services:
 postgres:
  image: postgres:13
  container_name: postgres_container
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: postgres
   POSTGRES_DB: postgres
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data
  restart: always 
 app:
  build: "./app"
  container_name: node-container
  restart: always
  volumes:
   - ./app:/home/node/app 
  ports:
   - "8080:8080"
  depends_on:
      - postgres
  
    